externalfunc=stdout 0 2
externalfunc=stdin 2 0
externalfunc=sqrt 4 4
externalfunc=atan2 4 8
externalfunc=sin 4 4
externalfunc=cos 4 4
externalfunc=tan 4 4
externalfunc=asin 4 4
externalfunc=acos 4 4
externalfunc=atan 4 4
externalfunc=random 4 0
externalfunc=wsend 0 16
externalfunc=wreceive 4 12
externalfunc=send 0 8
externalfunc=receive 4 8
externalfunc=radar 0 0
externalfunc=toglobal 0 4
externalfunc=tolocal 0 4
externalfunc=toglobald 0 4
externalfunc=tolocald 0 4
externalfunc=time 4 0
externalfunc=debug 0 13
externalfunc=ldebug 0 13
externalfunc=debug_label 0 16
externalfunc=ldebug_label 0 16
externalfunc=dequeue_command 4 4
externalfunc=gui_create 0 4
externalfunc=gui_destroy 0 4
externalfunc=gui_update 0 4
externalfunc=pendrive_plug 0 0
externalfunc=pendrive_unplug 0 0
externalfunc=pendrive_read 4 12
externalfunc=pendrive_write 4 12
